//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using MyFriendsAround.Common.Entities;

namespace MyFriendsAround.Data
{
    public partial class MyFriendsModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=MyFriendsModelContainer";
        public const string ContainerName = "MyFriendsModelContainer";
    
        #region Constructors
    
        public MyFriendsModelContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MyFriendsModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MyFriendsModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Friend> Friends
        {
            get { return _friends  ?? (_friends = CreateObjectSet<Friend>("Friends")); }
        }
        private ObjectSet<Friend> _friends;

        #endregion
    }
}
